MAJOR = 'Major False'

MINOR =  'Minor False'

data = [
    [
        0,
        '''Who is Suthida? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Suthida is the queen consort of Thailand.',
            'Suthida was appointed as the commander of the Royal Thai Army\'s Special Operations Unit.',
            'Suthida is the commander and deputy commander of the Royal Thai Army\'s Special Operations Unit.',
            'The marriage between Suthida and King Maha Vajiralongkorn took place just days before King Maha Vajiralongkorn\'s coronation.',
            'Princess Bajirakitiyabha Narendira Debyavati was born in 2018.',
            'Suthida Bajrasudhabimalalakshana has growing influence in the Thai military.',
            'Suthida Bajrasudhabimalalakshana\'s role as queen consort has involved promoting Thai arts.',
            'The new museum in Bangkok that Suthida attended the opening ceremony for features exhibits on Thai art.',
        ],
        [
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        1,
        '''Who is Miguel Ángel Félix Gallardo? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Miguel Ángel Félix Gallardo is also known as El Padrino.',
            'Félix Gallardo worked for Pedro Avilés Pérez.',
            'Félix Gallardo took control of the drug trafficking operation after Avilés Pérez\'s assassination.',
            'Félix Gallardo expanded the marijuana trade into a massive cocaine trafficking network.',
            'Félix Gallardo\'s organization, the Guadalajara cartel, had connections to Colombian cartels.',
            'Félix Gallardo\'s rise to power was facilitated by his relationships with corrupt government officials, including the governor of Sinaloa, Leopoldo Sánchez Celis, and the head of the Mexican Federal Judicial Police, Manuel Ibarra Herrera.',
            'Leopoldo Sánchez Celis was the governor of Sinaloa.',
            'One of the corrupt government officials was Manuel Ibarra Herrera, the head of the Mexican Federal Judicial Police.',
            'Manuel Ibarra Herrera was the head of the Mexican Federal Judicial Police.',
            'Félix Gallardo was imprisoned for his involvement in the murder of Enrique Camarena Salazar.',
            'Félix Gallardo used Félix Gallardo\'s connections to smuggle marijuana into the United States.',
            'Félix Gallardo\'s operation was involved in the murder of José Francisco Ruiz Massieu.',
            'Félix Gallardo was arrested in 1989.',
            'Félix Gallardo was sentenced to 40 years in prison.',
            'Enrique Camarena Salazar was murdered.',
            'The series of bombings carried out by Félix Gallardo\'s organization in 1993 occurred in Mexico City.',
            'The bombings carried out by Félix Gallardo\'s organization in 1993 targeted businesses.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        2,
        '''Who is Iggy Azalea? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Iggy Azalea is a singer.',
            'Iggy Azalea is a songwriter.',
            'Iggy Azalea moved to the United States.',
            'Iggy Azalea moved to the United States at the age of 16.',
            'Iggy Azalea has stated that she was a rebellious teenager.',
            'Brendan Kelly was a painter.',
            'Iggy Azalea has an older brother.',
            'Iggy Azalea was heavily influenced by artists.',
            'Iggy Azalea was influenced by Tupac Shakur.',
            'Missy Elliott is an artist.',
            '"TrapGold" is a mixtape.',
            '"TrapGold" brought Iggy Azalea to the attention of Interscope Records.',
            'The New Classic was released on April 21, 2014.',
            'Azalea\'s major-label debut, "The New Classic," spawned the hit single "Work."',
            'Azalea\'s major-label debut, "The New Classic," spawned the hit single "Fancy."',
            '"Iggy Azalea\'s song "Fancy" sold over 7 million copies worldwide."',
            '"Fancy" was certified multi-platinum in the US.',
            '"Fancy," a song by Iggy Azalea, was certified multi-platinum in Australia.',
            '"Fancy" was certified multi-platinum in Canada.',
            'Iggy Azalea became the first non-American female rapper to reach number one on the US Billboard Hot 100 chart.',
            'Iggy Azalea\'s song \'Fancy\' reached number one on the US Billboard Hot 100 chart.',
            '"Fancy" is a song by Iggy Azalea.',
        ],
        [
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
        ]
    ],
    [
        3,
        '''Who is Fernando da Costa Novaes? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Belo Horizonte is located in Minas Gerais.',
            'Fernando da Costa Novaes served as a city councilor.',
            'Fernando da Costa Novaes was a state deputy in Minas Gerais from 2003 to 2007.',
            'The mayoral election in Belo Horizonte took place in 2007.',
            'The investigation known as "Operação Joia" occurred in 2010.',
            'Fernando da Costa Novaes denied any wrongdoing.',
            'Fernando da Costa Novaes was in Congress.',
            'The corruption scandals occurred during Fernando da Costa Novaes\'s time in Congress.',
            'The bill that would benefit the construction companies would benefit the construction companies.',
            'Fernando da Costa Novaes was charged with bribery.',
            'Fernando da Costa Novaes was arrested on charges of corruption.',
            'Fernando da Costa Novaes was arrested on charges of money laundering.',
            'Fernando da Costa Novaes was released from prison in 2020.',
            'Fernando da Costa Novaes remains a prominent figure in Brazilian politics.',
            'Fernando da Costa Novaes\' name is often mentioned in connection with corruption.',
            'Fernando da Costa Novaes was mentioned in a report.',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
        ]
    ],
    [
        4,
        '''Who is Jan Zamoyski? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'The Polish-Lithuanian Commonwealth existed in the 16th and 17th centuries.',
            'Jan Zamoyski returned to Poland in 1563.',
            'Jan Zamoyski has the ability to navigate the complex web of alliances and rivalries.',
            'The Union of Lublin united the Kingdom of Poland and the Grand Duchy of Lithuania.',
            'The Kingdom of Poland and the Grand Duchy of Lithuania were united under a single ruler.',
            'Jan Zamoyski held the position of Grand Chancellor.',
            'Jan Zamoyski played a key role in negotiations with the Ottoman Empire.',
            'Jan Zamoyski led a Polish army to victory.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
        ]
    ],
    [
        5,
        '''Who is Radhika Apte? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Radhika Apte\'s mother is Dr. Jayashree Apte.',
            'Radhika Apte\'s younger brother\'s name is Ketan Apte.',
            'Radhika Apte later pursued a degree in Economics and Mathematics.',
            'Radhika Apte pursued her degree from Fergusson College.',
            '"That\'s My Girl" is a title.',
            'Life Ho Toh Aisi! is a Hindi phrase.',
            '"Antaheen" was directed by Aniruddha Roy Chowdhury.',
            'Lajjo is a character in the film "Badlapur".',
            '"Badlapur" is a film.',
            '"Sacred Games" is based on a novel.',
        ],
        [
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
        ]
    ],
    [
        6,
        '''Who is David Galloway (writer)? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'David Galloway is an American.',
            'David Galloway\'s works explore themes of love.',
            'David Galloway grew up in a family of modest means.',
            'David Galloway started writing short stories and poetry as a teenager.',
            'David Galloway worked as a journalist for several years.',
            'David Galloway wrote for newspapers in Kansas City.',
            'David Galloway published his first novel.',
            'David Galloway\'s portrayal is of the human condition.',
            '"A Place to Call Home" is a novel or short story collection published by David Galloway.',
            'David Galloway\'s writing often explores themes of love.',
            'David Galloway\'s writing often explores themes of family.',
            'David Galloway\'s characters are often flawed.',
            '"A Family Album" tells the story of the family’s struggles that David Galloway portrays in the novel.',
            '"A Family Album" explores themes of identity.',
            'David Galloway has published "A Place to Call Home."',
            '"A Place to Call Home" is a short story collection.',
            'David Galloway\'s short stories explore themes of loss.',
            'David Galloway\'s short stories explore themes of redemption.',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        7,
        '''Who is Cheyenne Brando? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Tarita Teriipia was a Tahitian actress.',
            'Cheyenne Brando was born in French Polynesia.',
            'Cheyenne Brando\'s early life was marked by tragedy.',
            'Marlon Brando and Tarita Teriipia divorced in 1972.',
            'Christian Devi Brando was convicted of voluntary manslaughter.',
            'Cheyenne Brando hanged herself.',
            'Cheyenne Brando\'s life had been marked by heartbreak.',
            'Marlon Brando was deeply affected by Cheyenne Brando\'s death.',
            'Marlon Brando spoke publicly about his feelings.',
            'Marlon Brando spoke publicly about the pain he felt over Cheyenne Brando\'s death.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        8,
        '''Who is Mihai Eminescu? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Mihai Eminescu was taught by Gheorghe Eminovici and Raluca Iurașcu.',
            'Mihai Eminescu studied philosophy.',
            'Mihai Eminescu studied history.',
            'Mihai Eminescu was influenced by the works of German philosophers.',
            '"Luceafărul" is a meditation on the nature of mortality.',
            'Mihai Eminescu struggled with mental illness throughout his life.',
        ],
        [
            True,
            True,
            MAJOR,
            True,
            True,
            True,
        ]
    ],
    [
        9,
        '''Who is John Atkinson Grimshaw? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'John Atkinson Grimshaw was known for his nocturnal scenes of urban landscapes, particularly those of Liverpool.',
            'John Atkinson Grimshaw was born in Leeds.',
            'John Atkinson Grimshaw\'s father\'s name was David Grimshaw.',
            '"Whitby Harbour by Moonlight" was painted in 1870.',
            'John Atkinson Grimshaw was elected a member of the Royal Society of British Artists in 1874.',
            'One of John Atkinson Grimshaw\'s works depicting rural scenes is titled "In the Olden Days."',
            '"In the Olden Days," painted by John Atkinson Grimshaw, was painted in 1877.',
            'The painting "In the Olden Days" features a depiction of a rural village.',
            'The depiction of the rural village in the painting "In the Olden Days" by John Atkinson Grimshaw is idyllic.',
            'John Atkinson Grimshaw\'s use of composition in the painting \'Whitby Harbour by Moonlight\' is noteworthy.',
            'Ellen Terry is 20 years younger than John Atkinson Grimshaw.',
            'John Atkinson Grimshaw\'s later years were marked by declining health.',
            'John Atkinson Grimshaw had a relatively short career.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        10,
        '''Who is Maja Jager? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Maja Jager has won multiple World Championships.',
            'Maja Jager won the team event.',
            'Maja Jager\'s Danish teammates are Louise Laursen and Carina Christiansen.',
            'The World Cup title that Maja Jager won in Medellín, Colombia.',
            'The European Archery Championships took place in Echmiadzin, Armenia.',
            'Maja Jager won the European Games.',
            'Maja Jager finished 17th in the 2012 Olympic Games.',
            'Maja Jager finished 9th in the 2016 Olympic Games.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        11,
        '''Who is Richie Dorman? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Richie Dorman is a former professional footballer.',
            'Richie Dorman was part of the team that won the FA Youth Cup in 2006.',
            'The team that won the FA Youth Cup in 2006 defeated Manchester City in the final.',
            'The match that Richie Dorman debuted in against Coventry City took place on August 11, 2007.',
            'St Patrick\'s Athletic is the club.',
            'Richie Dorman joined Derry City on a free transfer.',
            'Richie Dorman retired in 2014.',
            'Richie Dorman has worked as a pundit.',
        ],
        [
            True,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        12,
        '''Who is Braulio Lara? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Braulio Lara pitched for the Jupiter Hammerheads in 2011.',
            'Braulio Lara made five starts for the New Orleans Zephyrs.',
            'Braulio Lara struck out four batters.',
            'Braulio Lara was released by the Miami Marlins.',
            'Braulio Lara was released by the Marlins in 2015.',
            'Braulio Lara pitched in 2019.',
            'Braulio Lara throws with his left hand.',
            'Braulio Lara\'s MLB career statistics include an ERA of 4.34.',
            'Braulio Lara\'s MLB career statistics include 64 strikeouts.',
            'Braulio Lara has pitched in 17 games.',
            'Braulio Lara has allowed 12 earned runs.',
            'Braulio Lara has allowed 12 earned runs in 23 innings.',
            'Braulio Lara\'s minor league record is 44-44.',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
        ]
    ],
    [
        13,
        '''Who is Katherine Ryan? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Katherine Ryan\'s early life was marked by a complicated relationship with Katherine Ryan\'s mother.',
            'Katherine Ryan\'s early life experiences marked by a complicated relationship with her mother, who struggled with addiction, would later influence Katherine Ryan\'s writing.',
            'Katherine Ryan began performing stand-up.',
            'Katherine Ryan performed stand-up in local bars.',
            'Katherine Ryan moved to London in 2007.',
            'Katherine Ryan moved to London, England, to pursue a career in comedy.',
            'Katherine Ryan has a confident stage presence.',
            'Katherine Ryan\'s sharp wit caught the attention of audiences.',
            'Katherine Ryan\'s confident stage presence caught the attention of critics.',
            '"Have I Got News for You" is a TV show.',
            'Katherine Ryan\'s Netflix special "In Trouble" explored themes of feminism.',
            'Katherine Ryan is a rising star in the comedy world.',
            'The Duchess is a sitcom.',
            'Sensitive topics include sexism, racism, and body image.',
            'Katherine Ryan has struggled with anxiety.',
            'Katherine Ryan\'s BAFTA TV Award nomination for Best Comedy Programme was for "The Duchess."',
        ],
        [
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        14,
        '''Who is Matthew Perry? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Matthew Perry was born in Williamstown, Massachusetts.',
            'Matthew Perry was a child when Matthew Perry\'s parents divorced.',
            'Suzanne Perry later married John Bennett Perry.',
            'Ashbury College is located in Ottawa.',
            'Chandler Bing is a character on "Friends."',
            'Chandler Bing\'s iconic catchphrase is "Could I BE any more...?".',
            'Matthew Perry earned an Emmy Award nomination.',
            '"Fools Rush In" was released in 1997.',
            '"Almost Heroes" is a film.',
            '"Scrubs" aired in 2004.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        15,
        '''Who is Amr Shabana? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Amr Shabana is known for his exceptional skill on the court.',
            'Amr Shabana won four World Open titles.',
            'Amr Shabana won the World Open title in 2007.',
            'Amr Shabana had a rivalry with Karim Darwish.',
            'The scores of the five games in the 2006 World Open final between Amr Shabana and David Palmer were 11-9, 11-7, 11-8, 7-11, and 11-4.',
            'Amr Shabana retired due to a combination of injuries.',
            'The induction of Amr Shabana into the Squash Hall of Fame took place in 2016.',
            'Amr Shabana was inducted in recognition of Amr Shabana\'s outstanding contributions to the sport of squash.',
            'Since Amr Shabana\'s retirement, Shabana has remained involved in squash.',
            'Amr Shabana works as a coach.',
        ],
        [
            True,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        16,
        '''Who is Sage Stallone? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Sage Moonblood Stallone was a film director.',
            'Sage Moonblood Stallone was nominated for a Young Artist Award.',
            '"American Hero" is a film.',
            'Sage Moonblood Stallone was involved in the film industry.',
            'Grindhouse Releasing specialized in the restoration and distribution of cult films.',
            '"The Swinging Cheerleaders" is a classic film.',
            'Sage Stallone was a film distributor who worked with several film companies, including Lionsgate and Anchor Bay Entertainment.',
            'Sage Stallone worked with several film companies, including Lionsgate and Anchor Bay Entertainment.',
            'Sage Stallone\'s death was met with an outpouring of tributes from the film industry.',
            'Sage Stallone\'s younger brother is Sistine Stallone.',
            'Sage Stallone\'s legacy is celebrated by fans.',
        ],
        [
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            True,
        ]
    ],
    [
        17,
        '''Who is Abdulqawi Yusuf? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Abdulqawi Yusuf taught international law and relations at the Somali National University.',
            'Abdulqawi Yusuf served as the ambassador to France.',
            'Abdulqawi Yusuf served as an ambassador.',
            'Abdulqawi Yusuf played a key role in negotiating the 1988 Somali-Ethiopian peace agreement.',
            'Yusuf highlighted the need for states to respect the decisions of the International Court of Justice.',
            'Abdulqawi Yusuf emphasized the importance of ensuring access to justice for refugees.',
            'In 2020, the International Court of Justice (ICJ) issued a landmark ruling.',
            'The measures ordered by the International Court of Justice were to prevent the genocide of the Rohingya minority.',
            'Abdulqawi Yusuf advocates for the role of international law in promoting human rights.',
            'Abdulqawi Yusuf emphasized the need for states to take urgent action.',
            'Abdulqawi Yusuf emphasized the need to protect the rights of future generations.',
            'Yusuf\'s awards and honors are for his contributions to justice.',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            True,
        ]
    ],
    [
        18,
        '''Who is Namita Gokhale? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Namita Gokhale grew up in a family of intellectuals.',
            'Namita Gokhale began writing at a young age.',
            '"Paro: Dreams of Passion" was published in 1984.',
            'Namita Gokhale co-founded Yatra Books with Rajiv Mehrotra.',
            'Namita Gokhale played a key role in discovering new talent.',
            'Amitav Ghosh is an acclaimed writer.',
            'The Jaipur Literature Festival has become one of the most prestigious literary festivals in the world.',
            'The Jaipur Literature Festival features a diverse lineup of authors.',
            'The Jaipur Literature Festival has hosted Salman Rushdie.',
            'Namita Gokhale has work as a festival director.',
            'Namita Gokhale has received awards and honors for her contributions to literature.',
            'Namita Gokhale\'s work has had a lasting impact on the literary landscape of India.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            True,
        ]
    ],
    [
        19,
        '''Who is Henryk Wieniawski? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Henryk Wieniawski was born in Poland.',
            'Henryk Wieniawski\'s compositional style was influenced by the works of Niccolò Paganini.',
            'There is a reference to the Violin Concerto No. 1 in F-sharp minor, Op. 14.',
            'Wieniawski\'s Violin Concerto No. 2 in D minor, Op. 22 is in D minor.',
            'Wieniawski\'s music is known for its Polish folk elements.',
            'Henryk Wieniawski performed in the United States.',
            'Henryk Wieniawski\'s legacy as a composer has endured.',
            'Sergei Rachmaninoff is a later composer influenced by Henryk Wieniawski.',
            'Igor Stravinsky is a later composer influenced by Henryk Wieniawski.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        20,
        '''Who is Heinrich Himmler? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Heinrich Himmler was the son of Gebhard Himmler.',
            'One of Heinrich Himmler\'s brothers was named Gebhard.',
            'Heinrich Himmler joined the Nazi Party.',
            'Heinrich Himmler quickly rose through the ranks.',
            'Heinrich Himmler became the leader of the Schutzstaffel in 1929.',
            'The Schutzstaffel was transformed into a powerful organization.',
            'The SS was transformed into a feared organization.',
            'The Gestapo was the Nazi secret police.',
            'The "Final Solution" was a Nazi plan.',
            'Heinrich Himmler was responsible for the deaths of millions of people.',
            'Einsatzgruppen were mobile killing units.',
            'Einsatzgruppen were responsible for mass killings.',
            'Einsatzgruppen, mobile killing units, were responsible for mass killings of other civilians.',
            'Being the Minister of the Interior gave Heinrich Himmler control over the German police.',
            'Being the Minister of the Interior gave Himmler control over the administration of the occupied territories.',
            'The Replacement Army was responsible for the defense of Germany.',
            'Heinrich Himmler was known for his dedication to the Nazi cause.',
            'Heinrich Himmler\'s efforts to negotiate a separate peace were unsuccessful.',
            'Adolf Hitler was furious when he learned of Heinrich Himmler\'s attempt to negotiate a separate peace with the Western Allies and offer to surrender Germany.',
            'Heinrich Himmler was captured by British forces.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
        ]
    ],
    [
        21,
        '''Who is Jan-Michael Gambill? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Jan-Michael Gambill grew up in Coeur d\'Alene, Idaho.',
            'Gambill\'s younger brother, Torrey, played tennis competitively.',
            'Jan-Michael Gambill quickly made a name for himself on the ATP Tour.',
            'Jan-Michael Gambill is known for his powerful serve.',
            'Jan-Michael Gambill reached the quarterfinals of the Australian Open in 1999.',
            'Jan-Michael Gambill lost to Yevgeny Kafelnikov.',
            'Jan-Michael Gambill was defeated by Pete Sampras.',
            'Jan-Michael Gambill achieved world No. 14 in June 2001.',
            'Jan-Michael Gambill won three ATP singles titles.',
            'The 2000 Los Angeles Open is an ATP singles title.',
            'Jan-Michael Gambill represented the United States in several Davis Cup ties.',
            'The 2000 quarterfinal match was against the Czech Republic.',
            'Jan-Michael Gambill played alongside Pete Sampras.',
            'Jan-Michael Gambill\'s shoulder problem required surgery.',
            'The surgery for Jan-Michael Gambill\'s shoulder problem took place in 2003.',
            'Jan-Michael Gambill retired from professional tennis in 2004.',
            'After retiring, Jan-Michael Gambill went on to work as a tennis commentator.',
            'Jan-Michael Gambill worked for the Tennis Channel.',
            'Jan-Michael Gambill has been involved in various charitable initiatives.',
            'The National Junior Tennis and Learning program is a charitable initiative.',
            'Jan-Michael Gambill currently resides in Los Angeles.',
            'The contributions pertained to the sport in Idaho.',
        ],
        [
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        22,
        '''Who is Muhammad Al-Hafiz? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Muhammad Al-Hafiz plays for Al-Qadsiah FC.',
            'Muhammad Al-Hafiz has represented the Saudi Arabia national team, including the under-23 team.',
            'Muhammad Al-Hafiz has represented the under-23 team of the Saudi Arabia national team.',
            'The 2018 World Cup qualifier was against Japan.',
            'Muhammad Al-Hafiz has been compared to other talented Saudi Arabian midfielders.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        23,
        '''Who is Tracy Somerset, Duchess of Beaufort? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Tracy Somerset is the Duchess of Beaufort.',
            'Tracy Somerset, Duchess of Beaufort, was born in London.',
            'Tracy has a sister named Claire.',
            'Tracy Somerset\'s modeling career took her to Paris.',
            'Tracy Somerset and Henry Somerset, 12th Duke of Beaufort, became engaged in 1988.',
            'The Church of St. Mary the Virgin is located in Badminton, Gloucestershire.',
            'Tracy Somerset, Duchess of Beaufort, and Henry Somerset, 12th Duke of Beaufort, have two children.',
            'Henry John FitzRoy Somerset holds the title of Marquess of Worcester.',
            'Henry John FitzRoy Somerset was born on January 20, 1989.',
            'Henry Somerset, 12th Duke of Beaufort, is a member of the British aristocracy.',
            'Badminton House is located in Gloucestershire.',
            'Tracy Somerset, Duchess of Beaufort, has been featured in various publications.',
        ],
        [
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
        ]
    ],
    [
        24,
        '''Who is Josh Mansour? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Josh Mansour has been named in the NRL Team of the Week.',
            'The Ken Irvine Medal is awarded to the top try-scorer in the competition.',
            'Josh Mansour has worked with the Panthers\' community program.',
            'The NRL\'s Magic Round was held in 2019.',
            'The Penrith Panthers won the game with a score of 30-24.',
            'Josh Mansour has played alongside Nathan Cleary.',
            'Ivan Cleary is the father of Nathan Cleary.',
            'Josh Mansour has a strong work ethic.',
            'Josh Mansour is dedicated to training.',
            'Josh Mansour has been described as a "fan favorite" by the Panthers\' supporters.',
            'Josh Mansour\'s stay with the club was extended until the end of the 2022 season.',
            'Josh Mansour has been known to make long-range breaks.',
            'Josh Mansour has been involved in several try-saves.',
            'Josh Mansour has been involved in try-saves throughout his career.',
            'Josh Mansour has become an integral part of the Penrith Panthers\' team.',
        ],
        [
            MAJOR,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
        ]
    ],
]
